In [ ]:
from pathlib import Path
import sys

if (ppfolder := str(Path('..') / 'personal_python_packages')) not in sys.path:
    sys.path.append(ppfolder)

from LNECSPA import LTFdb

import numpy as np

In [28]:
tgtA = LTFdb()

In [29]:
file_path = Path(r'C:\Users\afons\OneDrive - Universidade de Lisboa\Controlo de Plataforma Sismica\LNEC_Adapta_Driver\LNEC_ERIES_RE-SAFE\CTL\TestLAquila\LAquilaReducedScale.tgt')
tgtA.read(file_path)

In [30]:
print(tgtA)

Filename: C:\Users\afons\OneDrive - Universidade de Lisboa\Controlo de Plataforma Sismica\LNEC_Adapta_Driver\LNEC_ERIES_RE-SAFE\CTL\TestLAquila\LAquilaReducedScale.tgt
AQTD: ['AQTD']
Stage: ["L'AQUILA-IT.AVZ.00.HNN.D.IT-2009 seismic record, scale factor 2/3, Cauchy+Froude similitude law"]
Obs: ['ERIES RE-Safe project']
Date: ['2024-07-19 12:18:26.272293']
Signals: 6


In [31]:
"""  LTF database.

LNEC Test File attributes
-------------------------
AQTD : str
    LabVIEW string.
stage : str
    LabVIEW string.
obs : str
    LabVIEW string.
date : str
    LabVIEW string.
t0 : ndarray
    LabVIEW array of timestamp.
dt : ndarray
    LabVIEW array of float64.
cluster : list of tuples [(scale, offset, digital),]
    scale : float
        LabVIEW float64.
    offset : float
        LabVIEW float64.
    digital : ndarray
        LabVIEW 1D array of int16.
dataformat : ndarray
    LabVIEW array of int32.
IDstring : list of strings
    LabVIEW array of string.
scalefactor : ndarray
    LabVIEW array of float64.
offset : ndarray
    LabVIEW array of float64.
names : list of strings
    LabVIEW array of string.
units : list of strings
    LabVIEW array of string.
types : list of strings
    LabVIEW array of string.
info : list of strings
    LabVIEW array of string.

Data attributes
---------------
_filename : str
    Name of file to read/write.
_eof : bool
    End-of-file indicator (True/False).
_data : list of ndarray
    Analog data as list of 1D `ndarray`.
data : ndarray
    Analog data as 2D `ndarray`. Deprecation warning: to be replaced by `_data`!

Properties
----------
filename : LTF filename
eof : LTF end-of-file has been reached?
metadata : `LTFdb` metadata
signals : `LTFdb` number of channels
samples : `LTFdb` number of samples per channel

Methods
-------
__init__ :
__str__ :
read : read LTF file
write : write LTF file
keys : channels keys
values : channels values
items : channels items
copy : 
update : update `LTFdb` in memory
append : append a new channel at the end of `LTFdb`
index : index channel names
extend : extend with data coming from a new LTF file or from another `LTFdb` instance
__len__ :
__getitem__ :
__setitem__ :
__deltitem__ :
__missing__ :
__iter__ :
__contains__ :
read_cluster : read LTF cluster
write_cluster : write LTF cluster
time : returns 1D time array
print_metadata : print metadata
print_data : print data
write_txt : write text file
waveforms : return LabVIEW waveforms (t0, dt, array)
dac : digital-to-analog conversion
adc : analog-to-digital conversion
 """
tgtA.print_metadata()

AQTD: ['AQTD']
Stage: ["L'AQUILA-IT.AVZ.00.HNN.D.IT-2009 seismic record, scale factor 2/3, Cauchy+Froude similitude law"]
Obs: ['ERIES RE-Safe project']
Date: ['2024-07-19 12:18:26.272293']
t0: [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
dt: [0.005 0.005 0.005 0.005 0.005 0.005]
Cluster: [(1.9440926740509248, 1.6826159119301773, array([5514, 5514, 5514, ..., 5514, 5514, 5514], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16)), (0.006608805059949585, 0.4583040592585605, array([1501, 1500, 1499, ..., 1493, 1495, 1499], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16))]
Dataformat: [0 0 0 0 0 0]
IDstring: ['IDstring', 'IDstring', 'IDstring', 'IDstring', 'IDstring', 'IDstring']
Scalefactor: [1. 1. 1. 1. 1. 1.]
Offset: [0. 0. 0. 0. 0. 0.]
Names: ['DispT', 'DispL', 'DispV', 'AccT', 'AccL', 'AccV']
Units: ['mm', 'mm', 'mm', 'g', 'g', 'g']


In [32]:
tgtA.print_data()

Data: [array([0.0002398, 0.0002398, 0.0002398, ..., 0.0002398, 0.0002398,
       0.0002398]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([-1.55446763e-06, -3.57131487e-06, -5.58816212e-06, ...,
       -1.76892456e-05, -1.36555511e-05, -5.58816212e-06]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])]


In [33]:
"""_data : list of ndarray
    Analog data as list of 1D `ndarray`."""
data_ = tgtA._data
print(np.ndim(data_))
print(np.shape(data_))
data_

2
(6, 8982)


[array([0.0002398, 0.0002398, 0.0002398, ..., 0.0002398, 0.0002398,
        0.0002398]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([-1.55446763e-06, -3.57131487e-06, -5.58816212e-06, ...,
        -1.76892456e-05, -1.36555511e-05, -5.58816212e-06]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.])]

In [34]:
for i in range(6):
    print("np.shape(data_["+str(i)+"]) = "+str(np.shape(data_[i])))

np.shape(data_[0]) = (8982,)
np.shape(data_[1]) = (8982,)
np.shape(data_[2]) = (8982,)
np.shape(data_[3]) = (8982,)
np.shape(data_[4]) = (8982,)
np.shape(data_[5]) = (8982,)


In [35]:
filename = file_path.name
tgtA.write_txt(filename+str(".txt"))