In [28]:
from pathlib import Path
import sys
if (ppfolder := str(Path('..') / 'personal_python_packages')) not in sys.path:
    sys.path.append(ppfolder)

from LNECSPA import LTFdb

import numpy as np

In [29]:
tgtA = LTFdb()

In [30]:
file_path = r'C:\Users\afons\OneDrive - Universidade de Lisboa\Controlo de Plataforma Sismica\LNEC_Adapta_Driver\LNEC_ERIES_RE-SAFE\CTL\TestLAquila\LAquilaReducedScale.tgt'
tgtA.read(file_path)

In [31]:
print(tgtA)

Filename: C:\Users\afons\OneDrive - Universidade de Lisboa\Controlo de Plataforma Sismica\LNEC_Adapta_Driver\LNEC_ERIES_RE-SAFE\CTL\TestLAquila\LAquilaReducedScale.tgt
AQTD: ['AQTD']
Stage: ["L'AQUILA-IT.AVZ.00.HNN.D.IT-2009 seismic record, scale factor 2/3, Cauchy+Froude similitude law"]
Obs: ['ERIES RE-Safe project']
Date: ['2024-07-19 12:18:26.272293']
Signals: 6


In [32]:
tgtA.print_metadata()

AQTD: ['AQTD']
Stage: ["L'AQUILA-IT.AVZ.00.HNN.D.IT-2009 seismic record, scale factor 2/3, Cauchy+Froude similitude law"]
Obs: ['ERIES RE-Safe project']
Date: ['2024-07-19 12:18:26.272293']
t0: [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
dt: [0.005 0.005 0.005 0.005 0.005 0.005]
Cluster: [(1.9440926740509248, 1.6826159119301773, array([5514, 5514, 5514, ..., 5514, 5514, 5514], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16)), (0.006608805059949585, 0.4583040592585605, array([1501, 1500, 1499, ..., 1493, 1495, 1499], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16)), (1.0, 0.0, array([0, 0, 0, ..., 0, 0, 0], dtype=int16))]
Dataformat: [0 0 0 0 0 0]
IDstring: ['IDstring', 'IDstring', 'IDstring', 'IDstring', 'IDstring', 'IDstring']
Scalefactor: [1. 1. 1. 1. 1. 1.]
Offset: [0. 0. 0. 0. 0. 0.]
Names: ['DispT', 'DispL', 'DispV', 'AccT', 'AccL', 'AccV']
Units: ['mm', 'mm', 'mm', 'g', 'g', 'g']


In [52]:
"""_data : list of ndarray
    Analog data as list of 1D `ndarray`."""
data_ = tgtA._data
print(np.ndim(data_))
print(np.shape(data_))
data_

2
(6, 8982)


[array([0.0002398, 0.0002398, 0.0002398, ..., 0.0002398, 0.0002398,
        0.0002398]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([-1.55446763e-06, -3.57131487e-06, -5.58816212e-06, ...,
        -1.76892456e-05, -1.36555511e-05, -5.58816212e-06]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.])]

In [51]:
"""     data : ndarray
        Analog data as 2D `ndarray`. Deprecation warning: to be replaced by `_data`! """
data = tgtA.data
print(np.ndim(data))
print(np.shape(data))
data

2
(6, 8982)


array([[ 2.39795826e-04,  2.39795826e-04,  2.39795826e-04, ...,
         2.39795826e-04,  2.39795826e-04,  2.39795826e-04],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.55446763e-06, -3.57131487e-06, -5.58816212e-06, ...,
        -1.76892456e-05, -1.36555511e-05, -5.58816212e-06],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [69]:
for i in range(6):
    print("np.shape(data_["+str(i)+"]) = "+str(np.shape(data[i])))

np.shape(data_[0]) = (8982,)
np.shape(data_[1]) = (8982,)
np.shape(data_[2]) = (8982,)
np.shape(data_[3]) = (8982,)
np.shape(data_[4]) = (8982,)
np.shape(data_[5]) = (8982,)
